# Generated by Django 4.0.2 on 2022-08-07 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercia', '0002_alter_product_created_by_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
